### ISSUE TITLE
Admin: Soldiers' Angels Admin

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#104]
@putn1nr 

Hi Nicole, 
under my log in I am not able to delete or archive an Angel or a service member.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. When we updated the Angel and Service Member "SA Status" rules, I believe we removed out the option of "Archive" (so that it matched your Status rules). Would you like us to add this back in as an "SA Status" or should there be an "Archive" button at the bottom of the page (say, next to the "Save" button)? Please advise on what you'd prefer. Thanks!
