### ISSUE TITLE
Angel Profile: My Opportunities

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#116]
The sentence under My opportunities  "has additional soldiers to assist it should be service members to assist"

![image](https://user-images.githubusercontent.com/46329541/61477725-259af900-a94d-11e9-96a1-815226ae7f6a.png)

**Comment by putn1nr** [comment]
@sa-sturner Hey Susie! Just wanted to tick this one off if possible (since it will be visable to Angels). However, not sure where the typo is. 

This is the text that is being displayed on the My Opportunities screen:

**My Opportunities**
Below are your service member opportunities. If you would like to assist with more opportunities, you may go to the Search Opportunities page and begin looking for additional soldiers to assist.

![image](https://user-images.githubusercontent.com/46578151/64724089-c5818880-d49f-11e9-9889-7ee39e65131a.png)

Please let me know what text correction(s) you'd like us to make. 

Thanks!
Nicole

**Comment by sa-sturner** [comment]
Instead of soldiers it should be service members.  The third word from the period.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Ah, got it now. We will get the text change implemented. Thanks!
