### ISSUE TITLE
Client - Deployed Sign In - Added Chaplain

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#38]
Signed in as service member and added that I was Chaplain.  Hit save.  No Chaplain questions were asked, even after hitting SAVE.

**Comment by tlcurran** [comment]
[Client - Deployed Sign In - Added Chaplain.pdf](https://github.com/pltarr/sa-database-testing/files/2804303/Client.-.Deployed.Sign.In.-.Added.Chaplain.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! I think this is a training item.

When logged in as a Service Member, if the "Are you a Chaplain" question is changed from = No to = Yes, then on the "Program Setting" tab, the Service Member would now have access to register for the Chaplain Support program (since initially he/she responsed "Are you a Chaplain" = No).

Clicking on the "Chaplain Support" Program would then allow the Service Member to answer the questions and submit/register for the Chaplain Support Program.

I would be happy to walk you through this process if you'd like - just let me know. Thanks!
