### ISSUE TITLE
Clients:  log in

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#76]
Service members must be able to log back into their profiles and upload documents etc. prior to them being approved.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We will update the logic here so that Service Members with an SA Status of = Pending and Approved can see the "Programs" tab in the Service Member Portal. This would allow the Service Member to be able to see Program responses and upload Program files AFTER the Registration process. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This item was completed as well. Service Members can now see the "Program Settings" and "My Account" tabs when logging in with an Approved or Pending SA Status. Let me know if you have any questions. Thanks!
